# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-20 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fictioc_Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(default='民谣', max_length=50, verbose_name='书名')),
                ('book_pub', models.CharField(default='民间流传', max_length=30, verbose_name='出版社')),
                ('book_price', models.DecimalField(decimal_places=2, default=None, max_digits=5, verbose_name='价格')),
                ('book_time', models.DateField(auto_now_add=True, verbose_name='上市时间')),
            ],
        ),
    ]
