# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-07 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='score',
            field=models.ImageField(default=0, null=True, upload_to='', verbose_name='分布式锁测试分数'),
        ),
    ]
