"""
Django settings for blogs project.

Generated by 'django-admin startproject' using Django 1.11.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1$1pmuej8xc@ou(z^x)z_f+*aacn6$a#b3-mo6r&!z*5qtn_9c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    "users",
    "tokens",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # csrf 验证
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blogs.urls'

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_METHODS = (  # 允许的接收的请求：
    'DELETE',  # 删除请求
    'GET',  # 获取请求
    'OPTIONS',  # 协商请求
    'PATCH',  # 局部更新
    'POST',  # 获取请求
    'PUT',  # 全部更新
)

CORS_ALLOW_HEADERS = (  # 当前支持的所有的header(头)
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',  # 请求加了"dnt"，不要给此推荐任何不相关的请求(广告等)(没啥用!不受约束)
    'origin',
    'user-agent',
    'x-csrftoken',  # 自由组织自己定义的header头，以 x- 开头
    'x-requested-with',
)

# CORS_PREFLIGHT_MAX_AGE  # 默认自带 86400s
#
# CORS_EXPOSE_HEADERS[]  # 前端想取后端自定义header头的内容,设置在其中
#
# CORS_ALLOW_CREDENTIALS  # 布尔值， 默认False # 跨域后是否设置使用cookie

APPEND_SLASH = False  # URL路径 APPEND_SLASH默认True:自动添加/,设置为False:不自动添加/

MEDIA_URL = "/media/" # 建议图片视频存储在此文件内

MEDIA_ROOT = os.path.join(BASE_DIR,"media/") # 自动拼接计算存储视频图片的位置


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blogs.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'blogs',  # 数据库名称,需要自己定义
        'USER': 'root',
        'PASSWORD': '123456',  # 管理员密码
        'HOST': '127.0.0.1',
        'PORT': 3306,
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

USE_I18N = True

USE_L10N = True

# TIME_ZONE = 'UTC'
TIME_ZONE = "Asia/Shanghai"   #<------------东八区时间，默认加八小时

# USE_TZ = True               #<-------------设置为True默认使用东八时区时间
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'   # JSS/CSS文件
