# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-17 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20190716_0348'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='booook',
        ),
    ]
